language: java

jdk:
- openjdk8
- openjdk12

git:
  depth: false
  quiet: true

before_cache:
- rm -f  $HOME/.gradle/caches/*/*.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
- ./gradlew check --no-daemon --no-build-cache --console=plain