/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.kszalontai.gcp.metric;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
